from __future__ import annotations

import json
from pathlib import Path

from rosadmin.service import contract_schema

_ARTIFACT = Path(__file__).resolve().parents[2] / "openapi.json"


def test_committed_openapi_matches_the_code():
    # The frontend builds against the committed openapi.json, regenerated by
    # scripts/dump_openapi.py. If a model or route changed without rerunning it,
    # this fails so the published contract cannot silently drift from the code.
    committed = json.loads(_ARTIFACT.read_text(encoding="utf-8"))
    assert committed == contract_schema()
